"""Initial schema from Phase 3 models

Revision ID: 63574c563c71
Revises:
Create Date: 2026-09-11 12:29:52.947416

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63574c563c71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("total_matches", sa.Integer(), nullable=True),
        sa.Column("total_wins", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("final_score_user", sa.Integer(), nullable=True),
        sa.Column("final_score_ai", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "psychology_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dominant_pattern", sa.String(length=30), nullable=True),
        sa.Column("lz_complexity_score", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "drift_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("detected_at_round", sa.Integer(), nullable=False),
        sa.Column("detector_method", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.CheckConstraint("severity IN ('warning','drift')"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "moves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("player_move", sa.Integer(), nullable=False),
        sa.Column("ai_move", sa.Integer(), nullable=False),
        sa.Column("result", sa.String(length=10), nullable=False),
        sa.Column("reaction_time_ms", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.CheckConstraint("result IN ('win','loss','draw')"),
        sa.CheckConstraint("ai_move IN (0,1,2)"),
        sa.CheckConstraint("player_move IN (0,1,2)"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("move_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=30), nullable=False),
        sa.Column("predicted_move", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["move_id"],
            ["moves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predictions")
    op.drop_table("moves")
    op.drop_table("drift_events")
    op.drop_table("psychology_profiles")
    op.drop_table("matches")
    op.drop_table("users")
    # ### end Alembic commands ###
